codecov: 
 token: 35309ef0-872a-4b8f-828a-ddc18855bdbc
comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
